In [1]:
import numpy as np
X = np.array([[2,0,0,0],[0,2,0,0],[0,0,1,0],[0,0,2,3],[0,0,0,1],[1,2,2,1]])

In [2]:
class LSA:
    
    def __init__(self,topic_num=2):
        self.topic_num = topic_num
        
    def fit(self,X):
        U,Sigma,V = np.linalg.svd(X)
        T,Y = U[:,:self.topic_num],(np.diag(Sigma).dot(V))[:self.topic_num,:]
        self.components = Y
        self.topic_vector = T
        
    def fit_transfrom(self,X):
        return self.topic_vector

In [3]:
clf = LSA(topic_num=2)
clf.fit(X)

In [4]:
print(clf.fit_transfrom(X))

[[-0.07843687 -0.28442303]
 [-0.15687373 -0.56884607]
 [-0.14262235  0.01379304]
 [-0.72880467  0.55349991]
 [-0.14785332  0.17530461]
 [-0.6291902  -0.50816689]]


In [5]:
print(clf.components)

[[-0.78606393 -1.57212786 -2.85861209 -2.96345752]
 [-1.07701296 -2.15402591  0.10445908  1.32763745]]
